name: Tests

permissions:
  contents: read
  pull-requests: read


on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  samplejob:
    if: ${{ !contains(github.event.head_commit.message, '--skip-pr') }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch base branch
        run: |
          base_branch="development"  # Replace with your actual base branch name
          git fetch origin $base_branch:$base_branch


      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git


      - name: Check if PR already exists
        id: check_pr
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          PR_EXISTS=$(gh pr list --head "$BRANCH_NAME" --json number --jq '. | length')
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_ENV


      - name: Run if PR exists
        if: env.pr_exists != '0'
        run: |
          echo "A PR from this branch already exists. Skipping creation."

      - name: Run if PR NOT exists
        if: env.pr_exists == '0'
        run: |
          echo "A PR from this branch already exists. Skipping creation."


   